"use strict";

const STORAGE_KEY = "aivm.creatorStudio.v1";
const EXAMPLE_IDEA = "A baby bear discovers the colors of the rainbow and learns them one by one.";
const DEFAULT_STATE = { projects: [], activeProjectId: null, profiles: { character: { name: "Main character", description: "Friendly, expressive main character; keep identity consistent.", wardrobe: "", traits: "", age: "" }, environment: { name: "Main world", description: "Bright, uncluttered environment with soft light.", details: "", lighting: "Soft natural light", props: "" }, style: { name: "Kids 3D Animation", description: "Polished child-friendly 3D animation.", palette: "Bright, cheerful, harmonious", camera: "Gentle cinematic movement", rules: "No text, no watermark, stable character design" } } };
let state = loadState();
let currentBlueprint = null;
const $ = (id) => document.getElementById(id);

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function escapeHTML(text) { return String(text).replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c])); }
function slug(text) { return String(text).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
function uid() { return "p-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8); }
function loadState() { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return clone(DEFAULT_STATE); const parsed = JSON.parse(raw); return { ...clone(DEFAULT_STATE), ...parsed, profiles: { ...clone(DEFAULT_STATE).profiles, ...(parsed.profiles || {}) } }; } catch { return clone(DEFAULT_STATE); } }
function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch { showToast("Local storage is unavailable."); } }
function showToast(message) { const toast = $("toast"); toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 1800); }
function activeProject() { return state.projects.find(p => p.id === state.activeProjectId) || null; }

function newProject(focus = true) {
  const project = { id: uid(), name: "Untitled Video", idea: "", type: "YouTube Short", length: 30, style: "Kids 3D Animation", includeCta: true, includeVoice: true, blueprint: null, updatedAt: Date.now() };
  state.projects.unshift(project); state.activeProjectId = project.id; persist(); renderProjectList(); loadProject(project); if (focus) $("projectName").focus(); showToast("New project created locally.");
}
function saveCurrentInputs() {
  const p = activeProject(); if (!p) return;
  p.name = $("projectName").value.trim() || "Untitled Video"; p.idea = $("idea").value.trim(); p.type = $("type").value; p.length = Number($("length").value); p.style = $("style").value; p.includeCta = $("includeCta").checked; p.includeVoice = $("includeVoice").checked; p.updatedAt = Date.now();
  persist(); renderProjectList();
}
function loadProject(project) {
  $("projectName").value = project.name || "Untitled Video"; $("idea").value = project.idea || ""; $("type").value = project.type || "YouTube Short"; $("length").value = String(project.length || 30); $("style").value = project.style || "Kids 3D Animation"; $("includeCta").checked = project.includeCta !== false; $("includeVoice").checked = project.includeVoice !== false; updateCount();
  currentBlueprint = project.blueprint ? clone(project.blueprint) : null;
  if (currentBlueprint) { renderBlueprint(currentBlueprint); $("results").classList.remove("hidden"); } else { $("results").classList.add("hidden"); }
  renderProjectList();
}
function renderProjectList() {
  const el = $("projectList");
  if (!state.projects.length) { el.innerHTML = '<div class="empty-projects">No projects yet.<br>Start your first video.</div>'; return; }
  el.innerHTML = state.projects.slice(0, 20).map(p => `<button class="project-item ${p.id === state.activeProjectId ? "active" : ""}" data-project-id="${escapeHTML(p.id)}" type="button"><span class="project-dot"></span><span class="project-copy"><b>${escapeHTML(p.name || "Untitled Video")}</b><small>${escapeHTML(p.type || "Video")} · ${p.blueprint ? `${p.blueprint.scenes.length} shots` : "Draft"}</small></span></button>`).join("");
}

function buildHook(idea, type) { const subject = slug(idea); return type === "Educational Video" ? `Can you discover the surprising lesson hidden in ${subject}?` : `Wait! You won't believe what happens when ${subject}!`; }
function buildScript(idea, scenes, includeCta) { const lines = scenes.map(s => s.voiceover).filter(Boolean); const parts = [`Here's a tiny adventure about ${idea.toLowerCase()}.`, ...lines]; if (includeCta) parts.push("What should we discover next? Follow for the next adventure!"); return parts.join(" "); }
function profilePrompt() {
  const c = state.profiles.character, e = state.profiles.environment, s = state.profiles.style;
  return `CHARACTER: ${c.name}. ${c.description} ${c.age ? `Age: ${c.age}.` : ""} ${c.traits ? `Traits: ${c.traits}.` : ""} ${c.wardrobe ? `Wardrobe: ${c.wardrobe}.` : ""} ENVIRONMENT: ${e.name}. ${e.description} ${e.details ? `Details: ${e.details}.` : ""} ${e.lighting ? `Lighting: ${e.lighting}.` : ""} ${e.props ? `Props: ${e.props}.` : ""} STYLE: ${s.name}. ${s.description} ${s.palette ? `Palette: ${s.palette}.` : ""} ${s.camera ? `Camera language: ${s.camera}.` : ""} ${s.rules ? `Rules: ${s.rules}.` : ""}`.replace(/\s+/g, " ").trim();
}
function buildScenes(idea, count, style, includeVoice) {
  const templates = [
    { action: `Open on the main subject noticing the key idea: ${idea}.`, camera: "Gentle cinematic push-in; keep the subject centered.", emotion: "Curious", environment: "Bright, uncluttered setting with soft light.", voiceover: "Look closely... something is about to happen!" },
    { action: `The subject moves toward the discovery and investigates ${idea}.`, camera: "Smooth tracking shot matching the subject's movement.", emotion: "Playful", environment: "Colorful environment with one clear visual focus.", voiceover: "Let's take a closer look!" },
    { action: `Reveal the most interesting part of ${idea} with a clear visual reaction.`, camera: "Medium shot into a gentle close-up on the discovery.", emotion: "Surprised", environment: "Warm, magical details without visual clutter.", voiceover: "Wow! Look what we found!" },
    { action: `The subject interacts with the discovery and demonstrates what is happening in ${idea}.`, camera: "Stable side angle followed by a small push-in.", emotion: "Fascinated", environment: "Friendly setting with consistent props and lighting.", voiceover: "We're learning something amazing!" },
    { action: `Introduce a tiny challenge connected to ${idea}; make the goal instantly understandable.`, camera: "Brief wider shot, then close on the character's reaction.", emotion: "Excited", environment: "Energetic but readable composition.", voiceover: "Oh! What happens next?" },
    { action: "The subject solves the challenge and celebrates the discovery.", camera: "Slow pull-back to reveal the complete scene.", emotion: "Joyful", environment: "Cheerful bright setting with gentle glow.", voiceover: "We did it! That was amazing!" },
    { action: `Give the audience a memorable final look at ${idea}.`, camera: "Friendly front-facing shot with a subtle push-in.", emotion: "Warm", environment: "Clean background with strong subject separation.", voiceover: "What a wonderful discovery!" },
    { action: "End with a simple visual payoff and a wave goodbye.", camera: "Wide ending shot, then a slow cinematic pull-back.", emotion: "Happy", environment: "Peaceful colorful environment with soft light.", voiceover: "See you on our next adventure!" }
  ];
  const continuity = profilePrompt();
  return Array.from({ length: count }, (_, index) => { const t = templates[index % templates.length]; const start = index * 5, end = start + 5; return { number: index + 1, start, end, action: t.action, camera: t.camera, emotion: t.emotion, environment: t.environment, voiceover: includeVoice ? t.voiceover : "", imagePrompt: `${style}; vertical 9:16; ${t.environment} ${t.action} Camera: ${t.camera} Emotion: ${t.emotion}. ${continuity} Maintain exact character identity, wardrobe, proportions, props, lighting direction and world design across every shot. High visual consistency, child-friendly, polished, clear silhouette, no text, no watermark.`, videoPrompt: `${t.action} ${t.camera} Character emotion: ${t.emotion}. ${continuity} Maintain exact identity and environment. Natural smooth movement, stable framing, subtle expressive motion, 5 seconds, vertical 9:16, no text, no watermark.` }; });
}
function calculateScore(idea, type, style) { let score = 72; if (idea.length >= 25) score += 7; if (idea.length >= 60) score += 4; if (["YouTube Short", "Instagram Reel", "TikTok"].includes(type)) score += 5; if (["Kids 3D Animation", "Cartoon", "Storybook"].includes(style)) score += 5; if (/who|how|why|discover|learn|secret|surprise/i.test(idea)) score += 4; return Math.min(97, score); }
function createTitle(idea, type) { const clean = idea.replace(/[.!?]+$/g, "").trim(); return type === "Educational Video" ? `Learn Something Amazing: ${clean} 📚` : `${clean} ✨ | A Tiny Adventure`; }
function createDescription(idea, type, cta) { const base = `A fun ${type.toLowerCase()} about ${idea.toLowerCase()}. Short, simple and designed for clear visual storytelling.`; return cta ? `${base} Follow for more creative adventures and new stories.` : base; }
function createHashtags(idea, type) { const tags = new Set(["#AIVideo", "#Shorts"]); if (/kids|baby|bear|child|rainbow|cartoon/i.test(idea)) ["#Kids", "#Animation", "#KidsContent"].forEach(x => tags.add(x)); if (type === "Educational Video") tags.add("#LearnWithMe"); if (type === "TikTok") tags.add("#TikTok"); if (type === "Instagram Reel") tags.add("#Reels"); return [...tags].join(" "); }
function makeIdeaList(idea) { const base = idea.replace(/[.!?]+$/g, "").trim(); return [`A surprising twist on ${base}`, `The tiny hero's biggest challenge: ${base}`, `What happens next? ${base}`, `A funny mistake while exploring ${base}`, `A simple lesson hidden inside ${base}`, `A magical version of ${base}`, `A friendship adventure inspired by ${base}`, `The secret behind ${base}`, `A 30-second challenge based on ${base}`, `The happiest ending for ${base}`]; }

function createVideo() {
  const idea = $("idea").value.trim(); if (!idea) { $("idea").focus(); showToast("Add a video idea first."); return; }
  saveCurrentInputs(); const p = activeProject(); const sceneCount = Math.max(3, Math.round(p.length / 5)); const scenes = buildScenes(p.idea, sceneCount, p.style, p.includeVoice); const blueprint = { idea: p.idea, type: p.type, length: p.length, style: p.style, includeCta: p.includeCta, includeVoice: p.includeVoice, hook: buildHook(p.idea, p.type), script: buildScript(p.idea, scenes, p.includeCta), scenes, score: calculateScore(p.idea, p.type, p.style), title: createTitle(p.idea, p.type), description: createDescription(p.idea, p.type, p.includeCta), hashtags: createHashtags(p.idea, p.type), ideas: makeIdeaList(p.idea), profiles: clone(state.profiles), updatedAt: Date.now() };
  currentBlueprint = blueprint; p.blueprint = clone(blueprint); p.updatedAt = Date.now(); persist(); renderProjectList(); renderBlueprint(blueprint); $("results").classList.remove("hidden"); $("results").scrollIntoView({ behavior: "smooth", block: "start" }); showToast("Blueprint saved locally.");
}

function renderBlueprint(data) {
  $("videoSummary").textContent = `${data.type} • ${data.length}s • ${data.style} • ${data.scenes.length} shots`;
  $("resultTitle").textContent = data.title; $("hook").textContent = data.hook; $("script").textContent = data.script; $("score").textContent = data.score; $("sceneCountBadge").textContent = `${data.scenes.length} × 5s shots`; $("title").textContent = data.title; $("description").textContent = data.description; $("hashtags").textContent = data.hashtags;
  $("ideaList").innerHTML = data.ideas.map((idea, i) => `<div class="idea-item"><b>${i + 1}.</b> ${escapeHTML(idea)}</div>`).join("");
  $("scenes").innerHTML = data.scenes.map((s, i) => `<div class="scene" data-scene-index="${i}"><div class="scene-head"><h4>Scene ${i + 1}</h4><div class="scene-tools"><button class="icon-button" data-action="up" data-index="${i}" type="button" ${i === 0 ? "disabled" : ""}>↑</button><button class="icon-button" data-action="down" data-index="${i}" type="button" ${i === data.scenes.length - 1 ? "disabled" : ""}>↓</button><button class="danger-button" data-action="delete" data-index="${i}" type="button">Delete</button><span class="timing">${s.start}s–${s.end}s</span></div></div><div class="scene-editor"><label>Action<textarea data-field="action">${escapeHTML(s.action)}</textarea></label><label>Camera<input data-field="camera" value="${escapeHTML(s.camera)}"></label><label>Emotion<input data-field="emotion" value="${escapeHTML(s.emotion)}"></label><label>Environment<input data-field="environment" value="${escapeHTML(s.environment)}"></label><label>Voiceover<textarea data-field="voiceover">${escapeHTML(s.voiceover)}</textarea></label><label>Image prompt<textarea data-field="imagePrompt">${escapeHTML(s.imagePrompt)}</textarea></label><label>Video prompt<textarea data-field="videoPrompt">${escapeHTML(s.videoPrompt)}</textarea></label></div></div>`).join("");
}
function syncScene(index) { const scene = currentBlueprint?.scenes[index]; const el = document.querySelector(`[data-scene-index="${index}"]`); if (!scene || !el) return; el.querySelectorAll("[data-field]").forEach(input => { scene[input.dataset.field] = input.value; }); scene.number = index + 1; scene.start = index * 5; scene.end = index * 5 + 5; persistBlueprintOnly(); }
function persistBlueprintOnly() { const p = activeProject(); if (!p || !currentBlueprint) return; p.blueprint = clone(currentBlueprint); p.updatedAt = Date.now(); persist(); renderProjectList(); }
function moveScene(index, direction) { const target = index + direction; if (!currentBlueprint || target < 0 || target >= currentBlueprint.scenes.length) return; [currentBlueprint.scenes[index], currentBlueprint.scenes[target]] = [currentBlueprint.scenes[target], currentBlueprint.scenes[index]]; currentBlueprint.scenes.forEach((s, i) => { s.number = i + 1; s.start = i * 5; s.end = i * 5 + 5; }); persistBlueprintOnly(); renderBlueprint(currentBlueprint); showToast("Scene order updated."); }
function deleteScene(index) { if (!currentBlueprint || currentBlueprint.scenes.length <= 3) return showToast("Keep at least 3 scenes."); currentBlueprint.scenes.splice(index, 1); currentBlueprint.length = currentBlueprint.scenes.length * 5; const p = activeProject(); if (p) { p.length = currentBlueprint.length; $("length").value = String(Math.min(60, Math.max(30, currentBlueprint.length))); } currentBlueprint.scenes.forEach((s, i) => { s.number = i + 1; s.start = i * 5; s.end = i * 5 + 5; }); persistBlueprintOnly(); renderBlueprint(currentBlueprint); showToast("Scene deleted."); }

function blueprintText(data) { return ["AI VIDEO MAKER — VIDEO BLUEPRINT", "=================================", "", `PROJECT: ${activeProject()?.name || "Untitled Video"}`, `IDEA: ${data.idea}`, `TYPE: ${data.type}`, `LENGTH: ${data.length} seconds`, `STYLE: ${data.style}`, `SCORE: ${data.score}/100`, "", `HOOK: ${data.hook}`, `SCRIPT: ${data.script}`, "", "SCENES", "======", "", ...data.scenes.flatMap(s => [`SCENE ${s.number} — ${s.start}s–${s.end}s`, `ACTION: ${s.action}`, `CAMERA: ${s.camera}`, `EMOTION: ${s.emotion}`, `ENVIRONMENT: ${s.environment}`, `IMAGE PROMPT: ${s.imagePrompt}`, `VIDEO PROMPT: ${s.videoPrompt}`, s.voiceover ? `VOICEOVER: ${s.voiceover}` : "", ""]), "PUBLISHING", "==========", `TITLE: ${data.title}`, `DESCRIPTION: ${data.description}`, `HASHTAGS: ${data.hashtags}`].join("\n"); }
function downloadFile(name, content, mime) { const blob = new Blob([content], { type: mime }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.rel = "noopener"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function downloadBlueprint() { if (currentBlueprint) downloadFile("ai-video-blueprint.txt", blueprintText(currentBlueprint), "text/plain;charset=utf-8"); else showToast("Create a blueprint first."); }
function downloadJSON() { if (currentBlueprint) downloadFile("ai-video-project.json", JSON.stringify({ project: activeProject(), profiles: state.profiles }, null, 2), "application/json;charset=utf-8"); else showToast("Create a blueprint first."); }
async function copyValue(value) { try { await navigator.clipboard.writeText(value); showToast("Copied."); } catch { showToast("Copy unavailable in this browser."); } }
async function copyAll() { if (currentBlueprint) copyValue(blueprintText(currentBlueprint)); else showToast("Create a blueprint first."); }
function regenerate() { createVideo(); }
function duplicateProject() { const p = activeProject(); if (!p) return; const copy = clone(p); copy.id = uid(); copy.name = `${p.name} Copy`; copy.updatedAt = Date.now(); state.projects.unshift(copy); state.activeProjectId = copy.id; persist(); loadProject(copy); showToast("Project duplicated."); }

function renderProfileForm(kind) {
  const p = state.profiles[kind]; const form = $("profileForm");
  if (kind === "character") form.innerHTML = `<label>Name<input data-profile-field="name" value="${escapeHTML(p.name)}"></label><label>Description<textarea data-profile-field="description">${escapeHTML(p.description)}</textarea></label><label>Age / proportions<input data-profile-field="age" value="${escapeHTML(p.age)}"></label><label>Traits<input data-profile-field="traits" value="${escapeHTML(p.traits)}"></label><label>Wardrobe / signature props<input data-profile-field="wardrobe" value="${escapeHTML(p.wardrobe)}"></label>`;
  if (kind === "environment") form.innerHTML = `<label>Name<input data-profile-field="name" value="${escapeHTML(p.name)}"></label><label>Description<textarea data-profile-field="description">${escapeHTML(p.description)}</textarea></label><label>World details<input data-profile-field="details" value="${escapeHTML(p.details)}"></label><label>Lighting<input data-profile-field="lighting" value="${escapeHTML(p.lighting)}"></label><label>Props / landmarks<input data-profile-field="props" value="${escapeHTML(p.props)}"></label>`;
  if (kind === "style") form.innerHTML = `<label>Name<input data-profile-field="name" value="${escapeHTML(p.name)}"></label><label>Description<textarea data-profile-field="description">${escapeHTML(p.description)}</textarea></label><label>Palette<input data-profile-field="palette" value="${escapeHTML(p.palette)}"></label><label>Camera language<input data-profile-field="camera" value="${escapeHTML(p.camera)}"></label><label>Non-negotiable rules<textarea data-profile-field="rules">${escapeHTML(p.rules)}</textarea></label>`;
}
function updateProfileField(input) { const kind = document.querySelector(".profile-tab.active")?.dataset.profile || "character"; state.profiles[kind][input.dataset.profileField] = input.value; persist(); if (currentBlueprint) { currentBlueprint.profiles = clone(state.profiles); persistBlueprintOnly(); } }
function updateCount() { $("charCount").textContent = `${$("idea").value.length} / 800`; }
function init() {
  renderProjectList(); if (!state.projects.length) newProject(false); else loadProject(activeProject()); renderProfileForm("character");
  $("idea").addEventListener("input", updateCount); $("newProjectBtn").addEventListener("click", () => newProject()); $("exampleBtn").addEventListener("click", () => { $("idea").value = EXAMPLE_IDEA; updateCount(); $("idea").focus(); }); $("createBtn").addEventListener("click", createVideo); $("downloadTxtBtn").addEventListener("click", downloadBlueprint); $("downloadJsonBtn").addEventListener("click", downloadJSON); $("copyAllBtn").addEventListener("click", copyAll); $("duplicateBtn").addEventListener("click", duplicateProject); $("regenerateBtn").addEventListener("click", regenerate);
  document.querySelectorAll(".profile-tab").forEach(btn => btn.addEventListener("click", () => { document.querySelectorAll(".profile-tab").forEach(b => b.classList.remove("active")); btn.classList.add("active"); renderProfileForm(btn.dataset.profile); }));
  document.addEventListener("click", event => { const project = event.target.closest("[data-project-id]"); if (project) { const p = state.projects.find(x => x.id === project.dataset.projectId); if (p) { saveCurrentInputs(); state.activeProjectId = p.id; persist(); loadProject(p); } return; } const action = event.target.closest("[data-action]"); if (action) { syncScene(Number(action.dataset.index)); const i = Number(action.dataset.index); if (action.dataset.action === "up") moveScene(i, -1); if (action.dataset.action === "down") moveScene(i, 1); if (action.dataset.action === "delete") deleteScene(i); return; } const tiny = event.target.closest("[data-copy-target]"); if (tiny) copyValue($(tiny.dataset.copyTarget).textContent); });
  document.addEventListener("input", event => { if (event.target.matches("[data-profile-field]")) updateProfileField(event.target); const field = event.target.closest("[data-scene-index]")?.querySelector("[data-field]"); if (field && event.target.matches("[data-field]")) syncScene(Number(event.target.closest("[data-scene-index]").dataset.sceneIndex)); });
  document.addEventListener("keydown", event => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") { event.preventDefault(); createVideo(); } });
}
document.addEventListener("DOMContentLoaded", init);
