"use strict";
(function(){
  const KEY="aivm.creatorStudio.v1", $=id=>document.getElementById(id);
  const clean=s=>String(s??"").replace(/\s+/g," ").trim(), esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}, save=s=>{try{localStorage.setItem(KEY,JSON.stringify(s));return true}catch{return false}};
  const active=s=>(s.projects||[]).find(p=>p.id===s.activeProjectId)||(s.projects||[])[0]||null, clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const locks=s=>{const p=s.profiles||{},c=p.character||{},e=p.environment||{},v=p.style||{};return{character:clean(`${c.name||"Main character"}. ${c.description||"Stable recognizable identity."} ${c.age?`Age ${c.age}.`:""} ${c.traits?`Traits: ${c.traits}.`:""} ${c.wardrobe?`Wardrobe: ${c.wardrobe}.`:""}`),world:clean(`${e.name||"Main world"}. ${e.description||"Stable setting."} ${e.details||""} ${e.lighting?`Lighting: ${e.lighting}.`:""} ${e.props?`Key props: ${e.props}.`:""}`),style:clean(`${v.name||"Polished cinematic style"}. ${v.description||""} ${v.palette?`Palette: ${v.palette}.`:""} ${v.camera?`Camera language: ${v.camera}.`:""}`),rules:clean(v.rules||"Stable design, clean composition, no text, no watermark")};};
  const subject=t=>clean(t).replace(/[.!?]+$/g,"")||"the main character's discovery";
  const templates={
    HOOK:{act:x=>`Reveal ${x} immediately through a visual mystery or surprising detail that creates one clear question.`,cam:"Clear medium-wide composition, gentle push-in.",emo:"curious",audio:"Tiny attention cue with a light musical lift."},
    SETUP:{act:x=>`Show the character noticing ${x} and making one clear choice that establishes the goal.`,cam:"Eye-level medium tracking shot.",emo:"hopeful",audio:"Light ambience with a simple rhythmic bed."},
    DESIRE:{act:x=>`Show the character actively pursuing the goal connected to ${x}. Make the desired result visually obvious.`,cam:"Smooth follow shot with one controlled move.",emo:"determined",audio:"Curious forward-moving pulse."},
    OBSTACLE:{act:x=>`Introduce one small, understandable obstacle related to ${x}. Keep the world stable while interrupting the plan.`,cam:"Stable medium framing with a controlled reaction close-up.",emo:"concerned",audio:"Brief tension accent with space for the reaction."},
    ESCALATION:{act:x=>`The character makes one stronger attempt involving ${x}; difficulty rises slightly while remaining easy to follow.`,cam:"Slightly tighter framing with measured forward movement.",emo:"frustrated then brave",audio:"Music rises one step with one action cue."},
    TURN:{act:x=>`Reveal one clear discovery, helper, or opportunity that changes how the character can solve the problem involving ${x}.`,cam:"Clean reveal with a small lateral move.",emo:"surprised and hopeful",audio:"Short reveal accent followed by hopeful music."},
    ATTEMPT:{act:x=>`The character uses the new idea to make one focused attempt toward the goal involving ${x}.`,cam:"Purposeful side angle with a gentle push toward the action.",emo:"focused",audio:"Rhythmic build with one movement cue."},
    PAYOFF:{act:x=>`Show direct cause and effect: the character's action produces the desired result involving ${x}, followed by a readable reaction.`,cam:"Close on the key action, then widen slightly for the reaction.",emo:"delighted",audio:"Warm resolution with one satisfying result cue."},
    MEMORY:{act:x=>`Hold on the strongest visual result of ${x} so the audience can absorb the emotion and remember the moment.`,cam:"Hero framing with very gentle drift.",emo:"joyful calm",audio:"Music opens and settles so the visual can breathe."},
    ENDING:{act:x=>`Close with a warm, earned final reaction that confirms the story is complete.`,cam:"Friendly medium shot with a tiny push-in; finish stable.",emo:"warm and happy",audio:"Short musical button with a clean tail."}
  };
  const beatMap={3:["HOOK","PAYOFF","ENDING"],4:["HOOK","SETUP","PAYOFF","ENDING"],5:["HOOK","SETUP","OBSTACLE","PAYOFF","ENDING"],6:["HOOK","SETUP","DESIRE","OBSTACLE","PAYOFF","ENDING"],7:["HOOK","SETUP","DESIRE","OBSTACLE","TURN","PAYOFF","ENDING"],8:["HOOK","SETUP","DESIRE","OBSTACLE","ESCALATION","PAYOFF","MEMORY","ENDING"],9:["HOOK","SETUP","DESIRE","OBSTACLE","ESCALATION","TURN","PAYOFF","MEMORY","ENDING"],10:["HOOK","SETUP","DESIRE","OBSTACLE","ESCALATION","TURN","ATTEMPT","PAYOFF","MEMORY","ENDING"],11:["HOOK","SETUP","DESIRE","OBSTACLE","ESCALATION","TURN","ATTEMPT","PAYOFF","MEMORY","ENDING","ENDING"],12:["HOOK","SETUP","DESIRE","OBSTACLE","ESCALATION","TURN","ATTEMPT","PAYOFF","MEMORY","MEMORY","ENDING","ENDING"]};
  const beats=n=>beatMap[n]||beatMap[6];
  function imagePrompt(p,role,t,l,i,n){return[`Vertical 9:16 ${p.style||"cinematic animation"}.`,`Story beat: ${role}. ${t.act(subject(p.idea))}`,`Character anchor: ${l.character}`,`World anchor: ${l.world}`,`Style anchor: ${l.style}`,`Composition: one dominant focal point; readable silhouette; clean foreground, midground and background separation; intentional depth; safe space for captions when needed.`,`Emotion: ${t.emo}.`,`Continuity: preserve identity, proportions, wardrobe, props, lighting direction, palette, world geometry, and screen direction across every shot.`,`Shot ${i+1} of ${n}; frame for a stable next-shot handoff.`,`Quality rules: ${l.rules}.`].join(" ");}
  function motionPrompt(role,t){const action=role==="PAYOFF"?"completes the key action and reacts with visible delight":role==="ENDING"?"settles into a warm final reaction and holds the ending pose":role==="MEMORY"?"makes a tiny natural movement while the result remains clear":"performs one clear physical action connected to the story";return[`Use the supplied image as the approved first frame.`,`Camera: ${t.cam}`,`Dominant subject action: ${action}.`,`Add only subtle secondary environmental motion already visible in the image.`,`5 seconds: start clearly, develop smoothly, reach a readable result, then settle into a stable final state.`,`Preserve identity, wardrobe, props, scene geometry, lighting direction, framing and screen direction. Do not redesign the scene.`].join(" ");}
  function check(ideaText,scenes,script){const text=clean(ideaText),roles=scenes.map(s=>s.role),hasHook=roles[0]==="HOOK",goal=roles.includes("SETUP")&&roles.includes("DESIRE"),conflict=roles.includes("OBSTACLE")||roles.includes("ESCALATION"),turn=scenes.length<7||roles.includes("TURN"),payoff=roles.includes("PAYOFF"),ending=roles.includes("ENDING"),oneAction=scenes.filter(s=>clean(s.dominantAction).length>10).length,continuity=scenes.filter(s=>clean(s.continuityInput).length>25).length,words=clean(script).split(/\s+/).filter(Boolean).length,voiceFit=words<=Math.max(45,Math.round(scenes.length*5*2.2));
    const story=(hasHook?7:0)+(goal?15:0)+(conflict?10:0)+(turn?4:0)+(payoff?9:0)+(ending?5:0),visual=15,motion=Math.round(15*oneAction/Math.max(1,scenes.length)),cont=Math.round(15*continuity/Math.max(1,scenes.length)),audio=voiceFit?5:2,input=text.length>=60?5:text.length>=30?4:2,score=clamp(story+visual+motion+cont+audio+input,0,94),issues=[];
    if(text.length<30)issues.push("Strengthen the idea with a specific subject, goal, and desired outcome."); if(!hasHook)issues.push("The first shot must be a true hook."); if(!goal)issues.push("Make the protagonist's goal visible before the obstacle."); if(!conflict)issues.push("Add one simple obstacle so the payoff feels earned."); if(!turn)issues.push("Add a meaningful turn before the payoff."); if(!payoff)issues.push("Add visible cause-and-effect payoff."); if(!ending)issues.push("Give the audience a clean ending."); if(oneAction<Math.ceil(scenes.length*.85))issues.push("Every shot needs one dominant physical action."); if(continuity<scenes.length)issues.push("Every shot needs a continuity handoff/state note."); if(!voiceFit)issues.push("Shorten voiceover to fit the runtime comfortably.");
    return{score,pass:score>=85&&issues.length===0,scores:{story,visual,motion,continuity:cont,audio,input},issues,gates:{hook:hasHook,goal,conflict,turn,payoff,ending,oneDominantAction:oneAction>=Math.ceil(scenes.length*.85),continuity:continuity===scenes.length,voiceFit}};}
  function make(p,s){const n=clamp(Math.round(Number(p.length||30)/5),3,12),roles=beats(n),l=locks(s),subjectText=subject(p.idea),scenes=roles.map((role,i)=>{const t=templates[role],next=roles[i+1]||null,first=i?`Begin from Shot ${i} final state; preserve pose, facing direction, prop state and lighting before movement.`:"Master reference: approved starting pose, facing direction and prop state.",last=role==="PAYOFF"?"Stable happy result; hold for transition.":role==="ENDING"?"Stable final reaction; clean hold for final frame.":`Stable end state that sets up the next beat (${next||"end"}).`,dominant=role==="PAYOFF"?"Complete the key action and react with delight":role==="ENDING"?"Settle into the final reaction and hold":role==="MEMORY"?"Make a tiny natural movement":"Perform one clear physical action connected to the story";return{number:i+1,start:i*5,end:i*5+5,role,action:t.act(subjectText),camera:t.cam,emotion:t.emo,environment:l.world,dominantAction:dominant,voiceover:p.includeVoice!==false?(role==="HOOK"?"Look closely... something is about to happen!":role==="PAYOFF"?"We did it!":role==="TURN"?"Wait... I know what we can do!":role==="ENDING"?"What a wonderful little adventure!":"Let's see what happens next!"):"",imagePrompt:imagePrompt(p,role,t,l,i,n),videoPrompt:motionPrompt(role,t),audioDirection:t.audio,continuityInput:first,firstFrameState:first,lastFrameState:last,nextShotHandoff:next?`Next shot begins from this final state: ${last}`:"Final state: hold cleanly for export.",negativePrompt:"Avoid identity drift, face changes, extra fingers or limbs, duplicated objects, warped props, texture flicker, lighting jumps, background redesign, camera jitter, unintended zooms, text, logos and watermarks."};});
    const script=scenes.map(x=>x.voiceover).filter(Boolean).join(" ")+(p.includeCta!==false?" Follow for the next little adventure!":""),qc=check(p.idea,scenes,script);return{version:4,idea:p.idea,type:p.type,length:scenes.length*5,style:p.style,includeCta:p.includeCta,includeVoice:p.includeVoice,hook:`First 2 seconds: create one unanswered question about ${subjectText.toLowerCase()}.`,script,scenes,score:qc.score,title:p.type==="Educational Video"?`Learn This: ${subjectText} 📚`:`${subjectText} ✨ | A Tiny Adventure`,description:"A story-first short with a clear goal, rising tension, cause-and-effect payoff, and continuity-controlled shots.",hashtags:"#Shorts #AIVideo #Animation #Storytelling",ideas:[],profiles:s.profiles||{},qualityDirector:true,storyPlan:{...storyPlan(p.idea,p.type),beats:roles},qc,updatedAt:Date.now()};}
  function storyPlan(text,type){const x=subject(text),edu=type==="Educational Video";return{premise:`A character faces a simple situation involving ${x}.`,centralQuestion:edu?`What can the viewer learn from ${x}?`:`What will happen when the character encounters ${x}?`,protagonistGoal:edu?`Understand or demonstrate the key idea behind ${x}.`:`Discover, solve, reach, or understand something connected to ${x}.`,obstacle:"One small visible problem makes the goal harder and gives the audience a reason to keep watching.",payoff:"The final result visibly follows from an earlier choice or action.",emotionalArc:"curiosity → hope → tension → determination → relief → joy",audiencePromise:edu?"One clear memorable takeaway.":"One clear question, rising anticipation, and an earned payoff."};}
  function renderQC(b){let p=$("qualityPanel");if(!p){p=document.createElement("div");p.id="qualityPanel";p.className="result-section quality-panel";const r=$("results");if(r)r.insertBefore(p,r.firstElementChild);}const q=b.qc||check(b.idea,b.scenes,b.script),status=q.pass?"READY TO GENERATE":"NEEDS REFINEMENT",g=Object.entries(q.gates).map(([k,v])=>`<span class="qc-gate ${v?"pass":"fail"}">${v?"✓":"!"} ${esc(k)}</span>`).join("");p.innerHTML=`<div class="section-label">QUALITY GATE</div><div class="qc-heading"><h3>${status}</h3><strong>${q.score}/100</strong></div><p class="helper">Story ${q.scores.story}/50 · Visual ${q.scores.visual}/15 · Motion ${q.scores.motion}/15 · Continuity ${q.scores.continuity}/15 · Audio ${q.scores.audio}/5 · Input ${q.scores.input}/5</p><div class="qc-gates">${g}</div>${q.issues.map(x=>`<div class="idea-item qc-issue">⚠ ${esc(x)}</div>`).join("")||'<div class="idea-item qc-pass">✓ All quality gates passed.</div>'}<button id="qualityRecheckBtn" class="secondary-button" type="button">↻ Recheck quality</button>`;$("qualityRecheckBtn").onclick=()=>{const s=read(),p=active(s);if(!p?.blueprint)return;p.blueprint.qc=check(p.blueprint.idea,p.blueprint.scenes,p.blueprint.script);p.blueprint.score=p.blueprint.qc.score;save(s);render(p.blueprint);};}
  function render(b){$("videoSummary").textContent=`${b.type} • ${b.length}s • ${b.style} • ${b.scenes.length} shots • Quality Director v4`;$("resultTitle").textContent=b.title;$("hook").textContent=b.hook;$("script").textContent=b.script;$("score").textContent=b.score;$("sceneCountBadge").textContent=`${b.scenes.length} × 5s shots`;$("title").textContent=b.title;$("description").textContent=b.description;$("hashtags").textContent=b.hashtags;$("ideaList").innerHTML=b.scenes.map((x,i)=>`<div class="idea-item"><b>${i+1}.</b> ${esc(x.role)} — ${esc(x.action)}</div>`).join("");$("scenes").innerHTML=b.scenes.map((x,i)=>`<div class="scene" data-scene-index="${i}"><div class="scene-head"><h4>Scene ${i+1} · ${esc(x.role)}</h4><div class="scene-tools"><span class="timing">${x.start}s–${x.end}s</span></div></div><div class="scene-editor"><label>Story action<textarea data-field="action">${esc(x.action)}</textarea></label><label>Dominant action<input data-field="dominantAction" value="${esc(x.dominantAction)}"></label><label>Camera<input data-field="camera" value="${esc(x.camera)}"></label><label>Emotion<input data-field="emotion" value="${esc(x.emotion)}"></label><label>Environment<input data-field="environment" value="${esc(x.environment)}"></label><label>Voiceover<textarea data-field="voiceover">${esc(x.voiceover)}</textarea></label><label>Image prompt<textarea data-field="imagePrompt">${esc(x.imagePrompt)}</textarea></label><label>Image-to-video motion<textarea data-field="videoPrompt">${esc(x.videoPrompt)}</textarea></label><label>Audio direction<input data-field="audioDirection" value="${esc(x.audioDirection)}"></label><label>First-frame state<input data-field="firstFrameState" value="${esc(x.firstFrameState)}"></label><label>Last-frame state<input data-field="lastFrameState" value="${esc(x.lastFrameState)}"></label><label>Next-shot handoff<input data-field="nextShotHandoff" value="${esc(x.nextShotHandoff)}"></label><label>Continuity handoff<input data-field="continuityInput" value="${esc(x.continuityInput)}"></label><label>Negative / failure safeguards<textarea data-field="negativePrompt">${esc(x.negativePrompt)}</textarea></label></div></div>`).join("");$("results").classList.remove("hidden");renderQC(b);}
  function run(){const s=read(),p=active(s);if(!p){$("newProjectBtn")?.click();return}const idea=$("idea"),text=clean(idea?.value);if(!text){idea?.focus();return}p.name=clean($("projectName")?.value)||p.name||"Untitled Video";p.idea=text;p.type=$("type")?.value||p.type;p.length=Number($("length")?.value||p.length||30);p.style=$("style")?.value||p.style;p.includeCta=$("includeCta")?.checked!==false;p.includeVoice=$("includeVoice")?.checked!==false;const b=make(p,s);p.blueprint=b;p.updatedAt=Date.now();s.activeProjectId=p.id;save(s);render(b);$("results")?.scrollIntoView({behavior:"smooth",block:"start"});}
  function install(){const c=$("createBtn");if(c&&!c.dataset.qdBound){c.dataset.qdBound="1";c.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();run();},true);}if(!$("qualityCreateBtn")&&c){const b=document.createElement("button");b.id="qualityCreateBtn";b.type="button";b.className="primary-button quality-button";b.textContent="✦ Create EXCELLENT video plan";c.insertAdjacentElement("afterend",b);b.addEventListener("click",run);}}
  window.AIVMQualityDirector={make,check,run,version:4};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();
