import test from 'node:test';import assert from 'node:assert/strict';import {createProject,planScenes,addAsset,updateAsset,regenerateScene,saveProject,loadProjects,moveScene,editScene,undoProject,reusableAsset,addProjectAudio,selectedProjectAudio,setSceneCaption,captionsForTimeline,validateProjectBackup,markMissingFiles} from './core.mjs';
test('local storyboard saves, versions, and respects locked assets during selective regeneration',()=>{let p=createProject('A child explores a magical garden','Garden');p.style='fantasy';p=planScenes(p,30);assert.equal(p.scenes.length,6);p=addAsset(p,p.scenes[0].id,{kind:'image',name:'Approved character'});const id=p.assets[0].id;p=updateAsset(p,id,'lock');const other=p.scenes[1];p=regenerateScene(p,other.id);assert.equal(p.assets[0].locked,true);assert.equal(p.scenes[0].status,'planned');p=regenerateScene(p,p.scenes[0].id);assert.deepEqual(p.scenes[0].assetIds,[id]);assert.throws(()=>updateAsset(p,id,'regenerate'),/Unlock/);const data=new Map();const storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};saveProject(storage,p);assert.equal(loadProjects(storage)[0].revision,p.revision);assert.ok(p.history.length>0);});
test('blank prompt fails',()=>assert.throws(()=>createProject('  '),/idea/));

test('timeline move and prompt edit preserve locked asset links and undo',()=>{let p=planScenes(createProject('A robot finds a key'),15);const first=p.scenes[0].id,second=p.scenes[1].id;p=addAsset(p,first,{kind:'image',name:'approved'});p=updateAsset(p,p.assets[0].id,'lock');p=moveScene(p,first,1);assert.equal(p.scenes[1].id,first);assert.equal(p.scenes[0].id,second);assert.equal(p.scenes[1].assetIds[0],p.assets[0].id);const before=p;p=editScene(p,second,'New action in the same world');assert.equal(p.scenes[0].prompt,'New action in the same world');p=undoProject(p);assert.deepEqual(p.scenes,before.scenes);assert.equal(p.assets[0].locked,true);assert.throws(()=>moveScene(p,second,-1),/Cannot move/);assert.throws(()=>editScene(p,first,'  '),/empty/);});

test('draft resumption favors approved assets and skips invalidated candidates',()=>{let p=planScenes(createProject('An astronaut finds a garden'),15);const scene=p.scenes[0].id;p=addAsset(p,scene,{kind:'image',name:'approved',sourcePath:'/local/a.ppm'});const approved=p.assets.at(-1).id;p=updateAsset(p,approved,'lock');p=addAsset(p,scene,{kind:'image',name:'new candidate',sourcePath:'/local/b.ppm'});assert.equal(reusableAsset(p,scene,'image').id,approved);p=regenerateScene(p,scene);assert.equal(reusableAsset(p,scene,'image').id,approved);assert.equal(reusableAsset(p,scene,'video'),null);});

test('project audio chooses latest role and rejects unknown role',()=>{let p=createProject('Small story');p=addProjectAudio(p,{role:'music',name:'one.wav',sourcePath:'/local/one.wav',size:100});p=addProjectAudio(p,{role:'music',name:'two.wav',sourcePath:'/local/two.wav',size:100});assert.equal(selectedProjectAudio(p,'music').name,'two.wav');assert.equal(selectedProjectAudio(p,'voice'),null);assert.throws(()=>addProjectAudio(p,{role:'paid',sourcePath:'/x'}),/role/);});

test('captions follow moved timeline and may be cleared',()=>{let p=planScenes(createProject('Two scenes'),10);const first=p.scenes[0].id;p=setSceneCaption(p,first,'  Hello   world  ');assert.deepEqual(captionsForTimeline(p),[{start:0,end:5,text:'Hello world'}]);p=moveScene(p,first,1);assert.deepEqual(captionsForTimeline(p),[{start:5,end:10,text:'Hello world'}]);p=setSceneCaption(p,first,'');assert.deepEqual(captionsForTimeline(p),[]);assert.throws(()=>setSceneCaption(p,first,'x'.repeat(161)),/long/);});

test('metadata recovery validates schema and marks unavailable files',()=>{let p=planScenes(createProject('A small story'),15);p=addAsset(p,p.scenes[0].id,{kind:'image',name:'still',sourcePath:'/old/path',hasFile:true});const parsed=validateProjectBackup(JSON.parse(JSON.stringify(p)));const restored=markMissingFiles(parsed,[p.assets[0].id]);assert.equal(restored.assets[0].sourcePath,null);assert.equal(restored.assets[0].status,'missing local file');assert.equal(p.assets[0].sourcePath,'/old/path');assert.throws(()=>validateProjectBackup({...p,costMode:'PAID'}),/FREE ONLY/);assert.throws(()=>validateProjectBackup({...p,scenes:[...p.scenes,p.scenes[0]]}),/invalid/);});
