export const KEY='aivm.v2.projects.v1';
const id=()=>crypto.randomUUID();
export function createProject(prompt,name='Untitled project'){
 if(!prompt?.trim())throw Error('Enter a video idea.');const now=new Date().toISOString();return{schema:1,id:id(),name:name.trim()||'Untitled project',prompt:prompt.trim(),style:'custom',hardwareMode:'light',bible:{character:'',world:'',visualRules:''},costMode:'FREE ONLY',createdAt:now,updatedAt:now,revision:1,scenes:[],assets:[],history:[]};
}
export function revise(old,next){const snapshot={revision:old.revision,name:old.name,prompt:old.prompt,style:old.style,hardwareMode:old.hardwareMode,bible:old.bible,scenes:old.scenes,assets:old.assets,at:old.updatedAt};return{...next,revision:old.revision+1,updatedAt:new Date().toISOString(),history:[...old.history,snapshot].slice(-10)};}
export function planScenes(project,seconds=30){const beats=['Establish setting and subject','Introduce the goal','Show an action','Develop the action','Show the result','Close with a visual payoff'];const count=Math.min(12,Math.max(1,Math.ceil(seconds/5)));return revise(project,{...project,scenes:Array.from({length:count},(_,i)=>{const beat=beats[Math.min(5,Math.floor(i*6/count))];return{id:id(),order:i+1,duration:Math.min(5,seconds-i*5),beat,prompt:`${project.prompt}\nStyle: ${project.style}. Scene ${i+1}/${count}: ${beat}. Preserve identity, wardrobe, setting, lighting direction and object positions across cuts.`,status:'planned',assetIds:[]};})});}
export function addAsset(project,sceneId,asset){if(!project.scenes.some(s=>s.id===sceneId))throw Error('Scene missing.');const assetId=id();return revise(project,{...project,assets:[...project.assets,{id:assetId,sceneId,kind:asset.kind,name:asset.name,hasFile:!!asset.hasFile,size:asset.size||0,duration:asset.duration||null,sourcePath:asset.sourcePath||null,provider:asset.provider||null,parentAssetId:asset.parentAssetId||null,status:'candidate',locked:false,reference:false,createdAt:new Date().toISOString()}],scenes:project.scenes.map(s=>s.id===sceneId?{...s,assetIds:[...s.assetIds,assetId]}:s)});}
export function updateAsset(project,assetId,action){const asset=project.assets.find(a=>a.id===assetId);if(!asset)throw Error('Asset missing.');if(action==='regenerate'&&asset.locked)throw Error('Unlock this asset before regenerating.');const changes={keep:{status:'kept'},lock:{locked:true},unlock:{locked:false},reference:{reference:true},later:{status:'animate later'},regenerate:{status:'needs regeneration'}}[action];if(!changes)throw Error('Unknown action.');return revise(project,{...project,assets:project.assets.map(a=>a.id===assetId?{...a,...changes}:action==='regenerate'&&asset.kind==='image'&&a.parentAssetId===assetId&&!a.locked?{...a,status:'needs regeneration'}:a)});}
export function regenerateScene(project,sceneId){if(!project.scenes.some(s=>s.id===sceneId))throw Error('Scene missing.');return revise(project,{...project,scenes:project.scenes.map(s=>s.id===sceneId?{...s,status:'needs regeneration',assetIds:s.assetIds}:s),assets:project.assets.map(a=>a.sceneId===sceneId&&!a.locked?{...a,status:'needs regeneration'}:a)});}
export function saveProject(storage,project){const all=JSON.parse(storage.getItem(KEY)||'{}');all[project.id]=project;storage.setItem(KEY,JSON.stringify(all));}
export function loadProjects(storage){return Object.values(JSON.parse(storage.getItem(KEY)||'{}'));}
export function moveScene(project,sceneId,direction){const from=project.scenes.findIndex(s=>s.id===sceneId);const to=from+direction;if(![-1,1].includes(direction)||from<0||to<0||to>=project.scenes.length)throw Error('Cannot move scene there.');const scenes=[...project.scenes];[scenes[from],scenes[to]]=[scenes[to],scenes[from]];return revise(project,{...project,scenes:scenes.map((s,i)=>({...s,order:i+1}))});}
export function editScene(project,sceneId,prompt){if(!prompt?.trim())throw Error('Scene prompt cannot be empty.');if(prompt.length>6000)throw Error('Scene prompt is too long.');if(!project.scenes.some(s=>s.id===sceneId))throw Error('Scene missing.');return revise(project,{...project,scenes:project.scenes.map(s=>s.id===sceneId?{...s,prompt:prompt.trim(),status:'edited'}:s)});}
export function undoProject(project){const snapshot=project.history.at(-1);if(!snapshot)throw Error('No earlier revision to restore.');return{...project,name:snapshot.name,prompt:snapshot.prompt,style:snapshot.style,hardwareMode:snapshot.hardwareMode,bible:snapshot.bible,scenes:snapshot.scenes,assets:snapshot.assets,revision:project.revision+1,updatedAt:new Date().toISOString(),history:project.history.slice(0,-1)};}
export function reusableAsset(project,sceneId,kind){const scene=project.scenes.find(s=>s.id===sceneId);const eligible=project.assets.filter(a=>a.sceneId===sceneId&&a.kind===kind&&a.sourcePath&&a.status!=='needs regeneration'&&(kind!=='video'||!Number.isFinite(a.duration)||a.duration>=scene.duration-0.5));return eligible.filter(a=>a.locked||a.status==='kept').at(-1)||eligible.at(-1)||null;}
export function addProjectAudio(project,audio){if(!['music','voice'].includes(audio.role))throw Error('Unsupported audio role.');if(!audio.sourcePath)throw Error('Audio must be imported into the local bridge.');const asset={id:id(),sceneId:null,kind:'audio',role:audio.role,name:audio.name,hasFile:true,size:audio.size,sourcePath:audio.sourcePath,provider:'local-import',status:'kept',locked:false,reference:false,createdAt:new Date().toISOString()};return revise(project,{...project,assets:[...project.assets,asset]});}
export function selectedProjectAudio(project,role){return project.assets.filter(a=>a.kind==='audio'&&a.role===role&&a.sourcePath&&a.status!=='needs regeneration').at(-1)||null;}
export function setSceneCaption(project,sceneId,caption){if(!project.scenes.some(s=>s.id===sceneId))throw Error('Scene missing.');const value=String(caption||'').replace(/\s+/g,' ').trim();if(value.length>160)throw Error('Caption is too long.');return revise(project,{...project,scenes:project.scenes.map(s=>s.id===sceneId?{...s,caption:value}:s)});}
export function captionsForTimeline(project){let start=0;const out=[];for(const scene of project.scenes){const end=start+scene.duration;if(scene.caption?.trim())out.push({start,end,text:scene.caption.trim()});start=end;}return out;}
export function validateProjectBackup(value){if(!value||value.schema!==1||typeof value.id!=='string'||typeof value.prompt!=='string'||value.prompt.length>10000||!Array.isArray(value.scenes)||value.scenes.length>200||!Array.isArray(value.assets)||value.assets.length>500)throw Error('Invalid V2 project backup.');if(value.costMode!=='FREE ONLY')throw Error('Only FREE ONLY V2 projects can be restored.');const sceneIds=new Set(value.scenes.map(s=>s.id));if(sceneIds.size!==value.scenes.length||value.scenes.some(s=>typeof s.id!=='string'||typeof s.prompt!=='string'||!Number.isFinite(s.duration)||s.duration<1||s.duration>60)||value.assets.some(a=>typeof a.id!=='string'||(a.sceneId!==null&&!sceneIds.has(a.sceneId))))throw Error('Backup scene or asset data is invalid.');return value;}
export function markMissingFiles(project,missingIds){const missing=new Set(missingIds);return {...project,assets:project.assets.map(a=>missing.has(a.id)?{...a,hasFile:false,sourcePath:null,status:'missing local file'}:a)};}
export function setBible(project,values){const character=String(values.character||'').trim(),world=String(values.world||'').trim(),visualRules=String(values.visualRules||'').trim();if([character,world,visualRules].some(v=>v.length>1200))throw Error('Each reference field must be 1200 characters or fewer.');return revise(project,{...project,bible:{character,world,visualRules}});}
export function compileScenePrompt(project,sceneId){const scene=project.scenes.find(s=>s.id===sceneId);if(!scene)throw Error('Scene missing.');const b=project.bible||{};return [scene.prompt,b.character&&`CHARACTER LOCK: ${b.character}`,b.world&&`WORLD LOCK: ${b.world}`,b.visualRules&&`VISUAL RULES: ${b.visualRules}`,'Preserve approved character identity and world details across scenes.'].filter(Boolean).join('\n');}
