export const KEY='aivm.v2.projects.v1';
const id=()=>crypto.randomUUID();
export function createProject(prompt,name='Untitled project'){
 if(!prompt?.trim())throw Error('Enter a video idea.');const now=new Date().toISOString();return{schema:1,id:id(),name:name.trim()||'Untitled project',prompt:prompt.trim(),style:'custom',costMode:'FREE ONLY',createdAt:now,updatedAt:now,revision:1,scenes:[],assets:[],history:[]};
}
export function revise(old,next){const snapshot={revision:old.revision,name:old.name,prompt:old.prompt,style:old.style,scenes:old.scenes,assets:old.assets,at:old.updatedAt};return{...next,revision:old.revision+1,updatedAt:new Date().toISOString(),history:[...old.history,snapshot].slice(-10)};}
export function planScenes(project,seconds=30){const beats=['Establish setting and subject','Introduce the goal','Show an action','Develop the action','Show the result','Close with a visual payoff'];const count=Math.min(12,Math.max(1,Math.ceil(seconds/5)));return revise(project,{...project,scenes:Array.from({length:count},(_,i)=>{const beat=beats[Math.min(5,Math.floor(i*6/count))];return{id:id(),order:i+1,duration:Math.min(5,seconds-i*5),beat,prompt:`${project.prompt}\nStyle: ${project.style}. Scene ${i+1}/${count}: ${beat}. Preserve identity, wardrobe, setting, lighting direction and object positions across cuts.`,status:'planned',assetIds:[]};})});}
export function addAsset(project,sceneId,asset){if(!project.scenes.some(s=>s.id===sceneId))throw Error('Scene missing.');const assetId=id();return revise(project,{...project,assets:[...project.assets,{id:assetId,sceneId,kind:asset.kind,name:asset.name,hasFile:!!asset.hasFile,size:asset.size||0,status:'candidate',locked:false,reference:false,createdAt:new Date().toISOString()}],scenes:project.scenes.map(s=>s.id===sceneId?{...s,assetIds:[...s.assetIds,assetId]}:s)});}
export function updateAsset(project,assetId,action){const asset=project.assets.find(a=>a.id===assetId);if(!asset)throw Error('Asset missing.');if(action==='regenerate'&&asset.locked)throw Error('Unlock this asset before regenerating.');const changes={keep:{status:'kept'},lock:{locked:true},unlock:{locked:false},reference:{reference:true},later:{status:'animate later'},regenerate:{status:'needs regeneration'}}[action];if(!changes)throw Error('Unknown action.');return revise(project,{...project,assets:project.assets.map(a=>a.id===assetId?{...a,...changes}:a)});}
export function regenerateScene(project,sceneId){if(!project.scenes.some(s=>s.id===sceneId))throw Error('Scene missing.');const locked=new Set(project.assets.filter(a=>a.locked).map(a=>a.id));return revise(project,{...project,scenes:project.scenes.map(s=>s.id===sceneId?{...s,status:'needs regeneration',assetIds:s.assetIds.filter(a=>locked.has(a))}:s),assets:project.assets.map(a=>a.sceneId===sceneId&&!a.locked?{...a,status:'needs regeneration'}:a)});}
export function saveProject(storage,project){const all=JSON.parse(storage.getItem(KEY)||'{}');all[project.id]=project;storage.setItem(KEY,JSON.stringify(all));}
export function loadProjects(storage){return Object.values(JSON.parse(storage.getItem(KEY)||'{}'));}
