import {createProject,planScenes,regenerateScene,addAsset,updateAsset,saveProject,loadProjects,revise,moveScene,editScene,undoProject} from './core.mjs';
import {putFile,getFile} from './file-store.mjs';
import {bridgeHealth,generateImage,animateImage,assembleVideo} from './local-provider.mjs';
import {decodePPM} from './ppm.mjs';
const el=id=>document.getElementById(id);let current=null;
function notice(message){el('notice').textContent=message;}
function persist(next){try{saveProject(localStorage,next);current=next;render();notice('Saved locally · revision '+next.revision);}catch(e){notice('Could not save: '+e.message);}}
function button(label,fn,secondary=false){const b=document.createElement('button');b.type='button';b.textContent=label;if(secondary)b.className='secondary';b.addEventListener('click',fn);return b;}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function generateScene(sceneId){const base=current;const scene=base.scenes.find(s=>s.id===sceneId);if(!scene)return;notice('Generating local preview for scene '+scene.order+'…');try{const result=await generateImage(scene.prompt);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed while generating. Retry this scene.');const next=addAsset(base,sceneId,{name:result.name,kind:'image',hasFile:true,size:result.blob.size,sourcePath:result.sourcePath,provider:result.provider});await putFile(next.assets.at(-1).id,result.blob);persist(next);notice('Local preview saved ('+result.provider+'). '+(result.note||''));}catch(e){notice('Generation stopped: '+e.message);}}
async function animateAsset(asset){const base=current;if(asset.locked&&asset.kind==='video'){notice('Locked video preserved.');return;}notice('Animating '+asset.name+' locally…');try{const scene=base.scenes.find(s=>s.id===asset.sceneId);const result=await animateImage(asset.sourcePath,scene.duration);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed while animating. Retry.');const next=addAsset(base,scene.id,{name:result.name,kind:'video',hasFile:true,size:result.blob.size,sourcePath:result.sourcePath,provider:result.provider});await putFile(next.assets.at(-1).id,result.blob);persist(next);notice('Motion clip saved ('+result.provider+'). '+(result.note||''));}catch(e){notice('Animation stopped: '+e.message);}}
async function assembleProject(){const base=current;if(!base?.scenes.length){notice('Create a scene plan first.');return;}const clips=base.scenes.map(scene=>base.assets.filter(a=>a.sceneId===scene.id&&a.kind==='video'&&a.sourcePath&&a.status!=='needs regeneration').at(-1));if(clips.some(c=>!c)){notice('Every scene needs a local motion clip before assembly.');return;}notice('Assembling final 1080p MP4; this may take time on a low-power laptop…');try{const result=await assembleVideo(clips.map(c=>c.sourcePath),base.scenes.reduce((n,s)=>n+s.duration,0));const host=el('finalVideo');host.replaceChildren();const link=document.createElement('a');link.href=result.url;link.download='aivm-v2-final.mp4';link.textContent='Download final MP4 ('+(result.bytes/1048576).toFixed(1)+' MB)';host.append(link);notice('Final MP4 passed bridge quality checks: '+result.media.video.width+'×'+result.media.video.height+'. Download before restarting the bridge.');}catch(e){notice('Assembly failed: '+e.message);}}
async function attachFile(sceneId,file){if(!file)return;if(file.size>100*1024*1024){notice('Maximum file size is 100 MB.');return;}const base=current;const next=addAsset(base,sceneId,{name:file.name,kind:file.type.split('/')[0]||'file',hasFile:true,size:file.size});const item=next.assets.at(-1);try{await putFile(item.id,file);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed during import. The file remains local but was not attached; import it again.');persist(next);}catch(e){notice('File was not saved; asset record was not added: '+e.message);}}
let previewUrl=null;
async function previewAsset(asset){try{const file=await getFile(asset.id);if(!file)throw Error('File missing from this browser.');const host=el('preview');host.replaceChildren();if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}let media;const type=file.type||'';if(asset.name.toLowerCase().endsWith('.ppm')){const {width,height,rgba}=decodePPM(await file.arrayBuffer());media=document.createElement('canvas');media.width=width;media.height=height;media.getContext('2d').putImageData(new ImageData(rgba,width,height),0,0);}else if(type.startsWith('image/')||type.startsWith('video/')||type.startsWith('audio/')){media=document.createElement(type.startsWith('image/')?'img':type.startsWith('video/')?'video':'audio');previewUrl=URL.createObjectURL(file);media.src=previewUrl;if(media.tagName!=='IMG')media.controls=true;}else throw Error('Preview is unavailable for this file type. Export it instead.');media.className='media-preview';host.append(media);notice('Showing '+asset.name);}catch(e){notice('Preview unavailable: '+e.message);}}
function render(){const list=el('projects');list.replaceChildren();for(const p of loadProjects(localStorage).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))){list.append(button(p.name,()=>{current=p;el('name').value=p.name;el('prompt').value=p.prompt;el('style').value=p.style;render();},true));}
 el('export').disabled=!current;el('undo').disabled=!current?.history?.length;const box=el('scenes');box.replaceChildren();el('summary').textContent=current?`${current.scenes.length} scenes · ${current.assets.length} asset records · revision ${current.revision} · FREE ONLY`:'';
 if(!current)return;
 for(const scene of current.scenes){const card=document.createElement('section');card.className='scene';const title=document.createElement('h3');title.textContent=`Scene ${scene.order} · ${scene.duration}s · ${scene.beat}`;card.append(title);const status=document.createElement('small');status.textContent=scene.status;card.append(status);const prompt=document.createElement('textarea');prompt.value=scene.prompt;prompt.rows=4;prompt.setAttribute('aria-label','Scene '+scene.order+' prompt');card.append(prompt);const controls=document.createElement('div');controls.className='actions';controls.append(button('Save scene prompt',()=>{try{persist(editScene(current,scene.id,prompt.value));}catch(e){notice(e.message);}},true),button('Move earlier',()=>{try{persist(moveScene(current,scene.id,-1));}catch(e){notice(e.message);}},true),button('Move later',()=>{try{persist(moveScene(current,scene.id,1));}catch(e){notice(e.message);}},true),button('Generate local preview',()=>generateScene(scene.id)),button('Revise this scene',()=>persist(regenerateScene(current,scene.id)),true),button('Import local file',()=>{const input=document.createElement('input');input.type='file';input.accept='image/*,video/*,audio/*';input.onchange=()=>attachFile(scene.id,input.files[0]);input.click();},true));card.append(controls);
 for(const asset of current.assets.filter(a=>a.sceneId===scene.id)){const row=document.createElement('div');row.className='scene';const label=document.createElement('p');label.textContent=`${asset.name} · ${asset.status}${asset.locked?' · LOCKED':''}${asset.reference?' · reference':''}`;row.append(label);const actions=document.createElement('div');actions.className='actions';for(const [text,action] of [['Keep','keep'],[asset.locked?'Unlock':'Lock',asset.locked?'unlock':'lock'],['Use as reference','reference'],['Animate later','later'],['Mark for regeneration','regenerate']])actions.append(button(text,()=>{try{persist(updateAsset(current,asset.id,action));}catch(e){notice(e.message);}},true));if(asset.kind==='image'&&asset.sourcePath)actions.append(button('Animate this still',()=>animateAsset(asset),true));if(asset.hasFile)actions.append(button('Preview',()=>previewAsset(asset),true));if(asset.hasFile)actions.append(button('Export file',async()=>{try{const file=await getFile(asset.id);if(!file)throw Error('File missing from this browser.');download(file,asset.name);}catch(e){notice(e.message);}},true));row.append(actions);card.append(row);}box.append(card);}
}
el('undo').addEventListener('click',()=>{try{const restored=undoProject(current);persist(restored);el('name').value=restored.name;el('prompt').value=restored.prompt;el('style').value=restored.style;}catch(e){notice(e.message);}});
el('assemble').addEventListener('click',assembleProject);
el('bridge').addEventListener('click',async()=>{try{const h=await bridgeHealth();notice(h.mock?'Bridge online in mock mode; no media will be created.':'Bridge online · local image preview available'+(h.imageFallback?.enabled?' via basic fallback.':'.'));}catch(e){notice('Local bridge unavailable. Run node local-bridge/server.mjs. '+e.message);}});
el('plan').addEventListener('click',()=>{try{const input=el('prompt').value;const name=el('name').value;let project=current&&current.prompt===input.trim()?revise(current,{...current,name:name.trim()||current.name,style:el('style').value}):createProject(input,name);project.style=el('style').value;if(project.scenes.length&&project.assets.length){notice('Asset records exist. Revise individual scenes to preserve them; the whole plan was preserved.');return;}persist(planScenes(project,Number(el('seconds').value)));}catch(e){notice(e.message);}});
el('export').addEventListener('click',()=>{if(!current)return;download(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),'aivm-v2-'+current.id+'.json');});
try{render();}catch(e){notice('Saved project data could not be read: '+e.message);}
