import {createProject,planScenes,regenerateScene,addAsset,updateAsset,saveProject,loadProjects,revise} from './core.mjs';
import {putFile,getFile} from './file-store.mjs';
const el=id=>document.getElementById(id);let current=null;
function notice(message){el('notice').textContent=message;}
function persist(next){try{saveProject(localStorage,next);current=next;render();notice('Saved locally · revision '+next.revision);}catch(e){notice('Could not save: '+e.message);}}
function button(label,fn,secondary=false){const b=document.createElement('button');b.type='button';b.textContent=label;if(secondary)b.className='secondary';b.addEventListener('click',fn);return b;}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function attachFile(sceneId,file){if(!file)return;if(file.size>100*1024*1024){notice('Maximum file size is 100 MB.');return;}const base=current;const next=addAsset(base,sceneId,{name:file.name,kind:file.type.split('/')[0]||'file',hasFile:true,size:file.size});const item=next.assets.at(-1);try{await putFile(item.id,file);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed during import. The file remains local but was not attached; import it again.');persist(next);}catch(e){notice('File was not saved; asset record was not added: '+e.message);}}
function render(){const list=el('projects');list.replaceChildren();for(const p of loadProjects(localStorage).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))){list.append(button(p.name,()=>{current=p;el('name').value=p.name;el('prompt').value=p.prompt;el('style').value=p.style;render();},true));}
 el('export').disabled=!current;const box=el('scenes');box.replaceChildren();el('summary').textContent=current?`${current.scenes.length} scenes · ${current.assets.length} asset records · revision ${current.revision} · FREE ONLY`:'';
 if(!current)return;
 for(const scene of current.scenes){const card=document.createElement('section');card.className='scene';const title=document.createElement('h3');title.textContent=`Scene ${scene.order} · ${scene.duration}s · ${scene.beat}`;card.append(title);const status=document.createElement('small');status.textContent=scene.status;card.append(status);const prompt=document.createElement('p');prompt.textContent=scene.prompt;card.append(prompt);const controls=document.createElement('div');controls.className='actions';controls.append(button('Revise this scene',()=>persist(regenerateScene(current,scene.id)),true),button('Import local file',()=>{const input=document.createElement('input');input.type='file';input.accept='image/*,video/*,audio/*';input.onchange=()=>attachFile(scene.id,input.files[0]);input.click();},true));card.append(controls);
 for(const asset of current.assets.filter(a=>a.sceneId===scene.id)){const row=document.createElement('div');row.className='scene';const label=document.createElement('p');label.textContent=`${asset.name} · ${asset.status}${asset.locked?' · LOCKED':''}${asset.reference?' · reference':''}`;row.append(label);const actions=document.createElement('div');actions.className='actions';for(const [text,action] of [['Keep','keep'],[asset.locked?'Unlock':'Lock',asset.locked?'unlock':'lock'],['Use as reference','reference'],['Animate later','later'],['Mark for regeneration','regenerate']])actions.append(button(text,()=>{try{persist(updateAsset(current,asset.id,action));}catch(e){notice(e.message);}},true));if(asset.hasFile)actions.append(button('Export file',async()=>{try{const file=await getFile(asset.id);if(!file)throw Error('File missing from this browser.');download(file,asset.name);}catch(e){notice(e.message);}},true));row.append(actions);card.append(row);}box.append(card);}
}
el('plan').addEventListener('click',()=>{try{const input=el('prompt').value;const name=el('name').value;let project=current&&current.prompt===input.trim()?revise(current,{...current,name:name.trim()||current.name,style:el('style').value}):createProject(input,name);project.style=el('style').value;if(project.scenes.length&&project.assets.length){notice('Asset records exist. Revise individual scenes to preserve them; the whole plan was preserved.');return;}persist(planScenes(project,Number(el('seconds').value)));}catch(e){notice(e.message);}});
el('export').addEventListener('click',()=>{if(!current)return;download(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),'aivm-v2-'+current.id+'.json');});
try{render();}catch(e){notice('Saved project data could not be read: '+e.message);}
