import {createProject,planScenes,regenerateScene,addAsset,updateAsset,saveProject,loadProjects,revise,moveScene,editScene,undoProject,reusableAsset,addProjectAudio,selectedProjectAudio,setSceneCaption,captionsForTimeline,validateProjectBackup,markMissingFiles,setBible,compileScenePrompt} from './core.mjs';
import {putFile,getFile} from './file-store.mjs';
import {bridgeHealth,generateImage,animateImage,assembleVideo,importAudio} from './local-provider.mjs';
import {decodePPM} from './ppm.mjs';
const el=id=>document.getElementById(id);let current=null;
function notice(message){el('notice').textContent=message;}
function persist(next){try{saveProject(localStorage,next);current=next;render();notice('Saved locally · revision '+next.revision);}catch(e){notice('Could not save: '+e.message);}}
function button(label,fn,secondary=false){const b=document.createElement('button');b.type='button';b.textContent=label;if(secondary)b.className='secondary';b.addEventListener('click',fn);return b;}
function fillBible(project){el('character').value=project.bible?.character||'';el('world').value=project.bible?.world||'';el('visualRules').value=project.bible?.visualRules||'';}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function generateScene(sceneId){const base=current;const scene=base.scenes.find(s=>s.id===sceneId);if(!scene)return;notice('Generating local preview for scene '+scene.order+'…');try{const result=await generateImage(compileScenePrompt(base,sceneId),base.hardwareMode);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed while generating. Retry this scene.');const next=addAsset(base,sceneId,{name:result.name,kind:'image',hasFile:true,size:result.blob.size,sourcePath:result.sourcePath,provider:result.provider});await putFile(next.assets.at(-1).id,result.blob);persist(next);notice('Local preview saved ('+result.provider+'). '+(result.note||''));return next.assets.at(-1);}catch(e){notice('Generation stopped: '+e.message);return null;}}
async function animateAsset(asset){const base=current;if(asset.locked&&asset.kind==='video'){notice('Locked video preserved.');return;}notice('Animating '+asset.name+' locally…');try{const scene=base.scenes.find(s=>s.id===asset.sceneId);const result=await animateImage(asset.sourcePath,scene.duration,base.hardwareMode);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed while animating. Retry.');const next=addAsset(base,scene.id,{name:result.name,kind:'video',hasFile:true,size:result.blob.size,sourcePath:result.sourcePath,provider:result.provider});await putFile(next.assets.at(-1).id,result.blob);persist(next);notice('Motion clip saved ('+result.provider+'). '+(result.note||''));return next.assets.at(-1);}catch(e){notice('Animation stopped: '+e.message);return null;}}
async function assembleProject(){const base=current;if(!base?.scenes.length){notice('Create a scene plan first.');return;}const clips=base.scenes.map(scene=>reusableAsset(base,scene.id,'video'));if(clips.some(c=>!c)){notice('Every scene needs a local motion clip before assembly.');return;}notice('Assembling final 1080p MP4; this may take time on a low-power laptop…');try{const result=await assembleVideo(clips.map(c=>c.sourcePath),base.scenes.reduce((n,s)=>n+s.duration,0),base.id,{musicPath:selectedProjectAudio(base,'music')?.sourcePath,voicePath:selectedProjectAudio(base,'voice')?.sourcePath,captions:captionsForTimeline(base)});const host=el('finalVideo');host.replaceChildren();const link=document.createElement('a');link.href=result.url;link.download='aivm-v2-final.mp4';link.textContent='Download final MP4 ('+(result.bytes/1048576).toFixed(1)+' MB)';host.append(link);notice('Final MP4 passed bridge quality checks: '+result.media.video.width+'×'+result.media.video.height+'. Download before restarting the bridge.');return result;}catch(e){notice('Assembly failed: '+e.message);return null;}}
async function createDraftVideo(){const projectId=current?.id;if(!projectId||!current.scenes.length){notice('Create a scene plan first.');return;}const button=el('createDraft');button.disabled=true;try{for(const [index,scene] of current.scenes.entries()){if(current.id!==projectId)throw Error('Project changed during production.');let clip=reusableAsset(current,scene.id,'video');if(clip)continue;notice('Scene '+(index+1)+'/'+current.scenes.length+': preparing still…');let still=reusableAsset(current,scene.id,'image');if(!still)still=await generateScene(scene.id);if(!still)throw Error('Scene '+(index+1)+' still failed. Previous assets are saved.');notice('Scene '+(index+1)+'/'+current.scenes.length+': rendering motion…');clip=await animateAsset(still);if(!clip)throw Error('Scene '+(index+1)+' clip failed. Previous assets are saved.');}const result=await assembleProject();if(!result)throw Error('Final assembly failed. Scene clips remain saved.');}catch(e){notice('Draft stopped: '+e.message);}finally{button.disabled=false;}}
async function attachFile(sceneId,file){if(!file)return;if(file.size>100*1024*1024){notice('Maximum file size is 100 MB.');return;}const base=current;const next=addAsset(base,sceneId,{name:file.name,kind:file.type.split('/')[0]||'file',hasFile:true,size:file.size});const item=next.assets.at(-1);try{await putFile(item.id,file);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed during import. The file remains local but was not attached; import it again.');persist(next);}catch(e){notice('File was not saved; asset record was not added: '+e.message);}}
let previewUrl=null;
async function previewAsset(asset){try{const file=await getFile(asset.id);if(!file)throw Error('File missing from this browser.');const host=el('preview');host.replaceChildren();if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}let media;const type=file.type||'';if(asset.name.toLowerCase().endsWith('.ppm')){const {width,height,rgba}=decodePPM(await file.arrayBuffer());media=document.createElement('canvas');media.width=width;media.height=height;media.getContext('2d').putImageData(new ImageData(rgba,width,height),0,0);}else if(type.startsWith('image/')||type.startsWith('video/')||type.startsWith('audio/')){media=document.createElement(type.startsWith('image/')?'img':type.startsWith('video/')?'video':'audio');previewUrl=URL.createObjectURL(file);media.src=previewUrl;if(media.tagName!=='IMG')media.controls=true;}else throw Error('Preview is unavailable for this file type. Export it instead.');media.className='media-preview';host.append(media);notice('Showing '+asset.name);}catch(e){notice('Preview unavailable: '+e.message);}}
function renderAssetBoard(project){const host=el('assetBoard');host.replaceChildren();if(!project)return;const filter=el('assetFilter').value;const assets=project.assets.filter(a=>filter==='all'||(filter==='locked'?a.locked:a.kind===filter));if(!assets.length){host.textContent='No assets in this view yet.';return;}for(const asset of assets){const row=document.createElement('div');row.className='asset-item';const scene=project.scenes.find(s=>s.id===asset.sceneId);const title=document.createElement('div');title.textContent=`${String(asset.kind||'file').toUpperCase()} · ${asset.name} · ${scene?'Scene '+scene.order:asset.role||'Project'} · ${asset.status}${asset.locked?' · LOCKED':''}`;row.append(title);const actions=document.createElement('div');actions.className='actions';if(asset.hasFile)actions.append(button('Preview',()=>previewAsset(asset),true),button('Export',async()=>{const file=await getFile(asset.id);if(file)download(file,asset.name);else notice('Asset file is missing in this browser.');},true));if(scene)actions.append(button('Go to scene',()=>el('scene-'+scene.id)?.scrollIntoView({behavior:'smooth'}),true));row.append(actions);host.append(row);}}
function render(){const list=el('projects');list.replaceChildren();for(const p of loadProjects(localStorage).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))){list.append(button(p.name,()=>{current=p;el('finalVideo').replaceChildren();el('preview').replaceChildren();el('name').value=p.name;el('prompt').value=p.prompt;el('style').value=p.style;el('hardware').value=p.hardwareMode||'light';fillBible(p);render();},true));}
 el('export').disabled=!current;el('undo').disabled=!current?.history?.length;const box=el('scenes');box.replaceChildren();el('summary').textContent=current?`${current.scenes.length} scenes · ${current.assets.length} asset records · revision ${current.revision} · FREE ONLY`:'';
 renderAssetBoard(current);if(!current){el('audioAssets').replaceChildren();return;}
 const audioHost=el('audioAssets');audioHost.replaceChildren();for(const role of ['music','voice']){const item=selectedProjectAudio(current,role);if(!item)continue;const row=document.createElement('div');row.className='actions';const text=document.createElement('span');text.textContent=role+': '+item.name;row.append(text,button('Preview',()=>previewAsset(item),true),button('Export file',async()=>{const file=await getFile(item.id);if(file)download(file,item.name);},true));audioHost.append(row);}
 for(const scene of current.scenes){const card=document.createElement('section');card.className='scene';card.id='scene-'+scene.id;const title=document.createElement('h3');title.textContent=`Scene ${scene.order} · ${scene.duration}s · ${scene.beat}`;card.append(title);const status=document.createElement('small');status.textContent=scene.status;card.append(status);const prompt=document.createElement('textarea');prompt.value=scene.prompt;prompt.rows=4;prompt.setAttribute('aria-label','Scene '+scene.order+' prompt');card.append(prompt);const caption=document.createElement('input');caption.value=scene.caption||'';caption.maxLength=160;caption.placeholder='Optional on-screen caption';caption.setAttribute('aria-label','Scene '+scene.order+' caption');card.append(caption);const controls=document.createElement('div');controls.className='actions';controls.append(button('Save caption',()=>{try{persist(setSceneCaption(current,scene.id,caption.value));}catch(e){notice(e.message);}},true),button('Save scene prompt',()=>{try{persist(editScene(current,scene.id,prompt.value));}catch(e){notice(e.message);}},true),button('Move earlier',()=>{try{persist(moveScene(current,scene.id,-1));}catch(e){notice(e.message);}},true),button('Move later',()=>{try{persist(moveScene(current,scene.id,1));}catch(e){notice(e.message);}},true),button('Generate local preview',()=>generateScene(scene.id)),button('Revise this scene',()=>persist(regenerateScene(current,scene.id)),true),button('Import local file',()=>{const input=document.createElement('input');input.type='file';input.accept='image/*,video/*,audio/*';input.onchange=()=>attachFile(scene.id,input.files[0]);input.click();},true));card.append(controls);
 for(const asset of current.assets.filter(a=>a.sceneId===scene.id)){const row=document.createElement('div');row.className='scene';const label=document.createElement('p');label.textContent=`${asset.name} · ${asset.status}${asset.locked?' · LOCKED':''}${asset.reference?' · reference':''}`;row.append(label);const actions=document.createElement('div');actions.className='actions';for(const [text,action] of [['Keep','keep'],[asset.locked?'Unlock':'Lock',asset.locked?'unlock':'lock'],['Use as reference','reference'],['Animate later','later'],['Mark for regeneration','regenerate']])actions.append(button(text,()=>{try{persist(updateAsset(current,asset.id,action));}catch(e){notice(e.message);}},true));if(asset.kind==='image'&&asset.sourcePath)actions.append(button('Animate this still',()=>animateAsset(asset),true));if(asset.hasFile)actions.append(button('Preview',()=>previewAsset(asset),true));if(asset.hasFile)actions.append(button('Export file',async()=>{try{const file=await getFile(asset.id);if(!file)throw Error('File missing from this browser.');download(file,asset.name);}catch(e){notice(e.message);}},true));row.append(actions);card.append(row);}box.append(card);}
}
el('assetFilter').addEventListener('change',()=>renderAssetBoard(current));
el('saveBible').addEventListener('click',()=>{if(!current){notice('Create a project first.');return;}try{persist(setBible(current,{character:el('character').value,world:el('world').value,visualRules:el('visualRules').value}));}catch(e){notice(e.message);}});
el('hardware').addEventListener('change',()=>{if(current)persist(revise(current,{...current,hardwareMode:el('hardware').value}));});
el('audioFile').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file||!current)return;const base=current;const role=el('audioRole').value;notice('Validating and importing audio locally…');try{const imported=await importAudio(file);if(current?.id!==base.id||current.revision!==base.revision)throw Error('Project changed during import.');const next=addProjectAudio(base,{role,name:file.name,size:file.size,sourcePath:imported.path});await putFile(next.assets.at(-1).id,file);persist(next);notice('Audio added: '+file.name+' ('+role+').');}catch(e){notice('Audio import failed: '+e.message);}finally{event.target.value='';}});
el('restore').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>1024*1024)throw Error('Project JSON exceeds 1 MB.');const backup=validateProjectBackup(JSON.parse(await file.text()));if(loadProjects(localStorage).some(p=>p.id===backup.id))throw Error('This project already exists here. Its saved data was left unchanged.');const missing=[];for(const asset of backup.assets){if(asset.hasFile&&!(await getFile(asset.id)))missing.push(asset.id);}const restored=markMissingFiles(backup,missing);saveProject(localStorage,restored);current=restored;el('name').value=restored.name;el('prompt').value=restored.prompt;el('style').value=restored.style;el('hardware').value=restored.hardwareMode||'light';fillBible(restored);render();notice('Project restored. '+missing.length+' media files are missing in this browser; re-import them by scene.');}catch(e){notice('Restore failed: '+e.message);}finally{event.target.value='';}});
el('undo').addEventListener('click',()=>{try{const restored=undoProject(current);persist(restored);el('name').value=restored.name;el('prompt').value=restored.prompt;el('style').value=restored.style;el('hardware').value=restored.hardwareMode||'light';fillBible(restored);}catch(e){notice(e.message);}});
el('createDraft').addEventListener('click',createDraftVideo);
el('assemble').addEventListener('click',assembleProject);
el('bridge').addEventListener('click',async()=>{try{const h=await bridgeHealth();notice(h.mock?'Bridge online in mock mode; no media will be created.':h.imageFallback?.enabled?'Bridge online · FREE ONLY basic still fallback enabled.':'Bridge online, but FREE ONLY image fallback is disabled.');}catch(e){notice('Local bridge unavailable. Run node local-bridge/server.mjs. '+e.message);}});
el('plan').addEventListener('click',()=>{try{const input=el('prompt').value;const name=el('name').value;let project=current&&current.prompt===input.trim()?revise(current,{...current,name:name.trim()||current.name,style:el('style').value,hardwareMode:el('hardware').value}):createProject(input,name);project.style=el('style').value;project.hardwareMode=el('hardware').value;if(!current||current.prompt!==input.trim())project.bible={character:el('character').value.trim(),world:el('world').value.trim(),visualRules:el('visualRules').value.trim()};if(project.scenes.length&&project.assets.length){notice('Asset records exist. Revise individual scenes to preserve them; the whole plan was preserved.');return;}persist(planScenes(project,Number(el('seconds').value)));}catch(e){notice(e.message);}});
el('export').addEventListener('click',()=>{if(!current)return;download(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),'aivm-v2-'+current.id+'.json');});
try{render();}catch(e){notice('Saved project data could not be read: '+e.message);}
